# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stickers.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stickers.proto',
  package='signalservice',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0estickers.proto\x12\rsignalservice\"\xbb\x01\n\x0bStickerPack\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x02 \x01(\t\x12\x31\n\x05\x63over\x18\x03 \x01(\x0b\x32\".signalservice.StickerPack.Sticker\x12\x34\n\x08stickers\x18\x04 \x03(\x0b\x32\".signalservice.StickerPack.Sticker\x1a$\n\x07Sticker\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05\x65moji\x18\x02 \x01(\t'
)




_STICKERPACK_STICKER = _descriptor.Descriptor(
  name='Sticker',
  full_name='signalservice.StickerPack.Sticker',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='signalservice.StickerPack.Sticker.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='emoji', full_name='signalservice.StickerPack.Sticker.emoji', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=221,
)

_STICKERPACK = _descriptor.Descriptor(
  name='StickerPack',
  full_name='signalservice.StickerPack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='signalservice.StickerPack.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author', full_name='signalservice.StickerPack.author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cover', full_name='signalservice.StickerPack.cover', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stickers', full_name='signalservice.StickerPack.stickers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STICKERPACK_STICKER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=221,
)

_STICKERPACK_STICKER.containing_type = _STICKERPACK
_STICKERPACK.fields_by_name['cover'].message_type = _STICKERPACK_STICKER
_STICKERPACK.fields_by_name['stickers'].message_type = _STICKERPACK_STICKER
DESCRIPTOR.message_types_by_name['StickerPack'] = _STICKERPACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StickerPack = _reflection.GeneratedProtocolMessageType('StickerPack', (_message.Message,), {

  'Sticker' : _reflection.GeneratedProtocolMessageType('Sticker', (_message.Message,), {
    'DESCRIPTOR' : _STICKERPACK_STICKER,
    '__module__' : 'stickers_pb2'
    # @@protoc_insertion_point(class_scope:signalservice.StickerPack.Sticker)
    })
  ,
  'DESCRIPTOR' : _STICKERPACK,
  '__module__' : 'stickers_pb2'
  # @@protoc_insertion_point(class_scope:signalservice.StickerPack)
  })
_sym_db.RegisterMessage(StickerPack)
_sym_db.RegisterMessage(StickerPack.Sticker)


# @@protoc_insertion_point(module_scope)
